#!/bin/sh
# =============================================================================
# ADCP Test Report Generator
# Runs CTest and produces a markdown report with execution statistics.
# Usage: ./scripts/test-report.sh [build_dir] [--xml-only]
# =============================================================================
set -eu

BUILD_DIR="${1:-build}"
XML_ONLY="${2:-}"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
REPORT_DIR="${BUILD_DIR}/test-reports"
REPORT="${REPORT_DIR}/report-$(date '+%Y%m%d_%H%M%S').md"

mkdir -p "${REPORT_DIR}"

# Build first
echo "=== Building ==="
cmake --build "${BUILD_DIR}" 2>&1 | tail -1

# Run tests
echo "=== Running Tests ==="
ctest --test-dir "${BUILD_DIR}" --output-on-failure -j4 2>&1 || true

# Generate report
echo "=== Generating Report ==="

cat > "${REPORT}" << EOF
# ADCP Test Report

**Generated:** ${TIMESTAMP}
**Build dir:** \`${BUILD_DIR}\`

## Test Results

| # | Name | Status | Time (s) | Labels |
|---|------|--------|----------|--------|
EOF

# Parse CTest output
ctest --test-dir "${BUILD_DIR}" -N 2>/dev/null | grep "Test #" | sort -t'#' -k2 -n | while read -r line; do
  NUM=$(echo "${line}" | sed -n 's/.*Test #\([0-9]*\).*/\1/p')
  NAME=$(echo "${line}" | sed -n 's/.*: \(.*\)/\1/p')
  echo "| ${NUM} | ${NAME} | — | — | — |" >> "${REPORT}"
done

# Summary with timing
echo "" >> "${REPORT}"
echo "## Summary" >> "${REPORT}"
echo "" >> "${REPORT}"

TOTAL=$(ctest --test-dir "${BUILD_DIR}" -N 2>/dev/null | grep -c "Test #" || echo "0")
PASSED=$(ctest --test-dir "${BUILD_DIR}" --no-tests=error 2>/dev/null | grep -c "passed" || echo "0")

echo "| Metric | Value |" >> "${REPORT}"
echo "|--------|-------|" >> "${REPORT}"
echo "| Total  | ${TOTAL} |" >> "${REPORT}"

# Individual timing info using ctest XML if available
if [ -f "${BUILD_DIR}/Testing/TAG" ]; then
  TAG=$(head -1 "${BUILD_DIR}/Testing/TAG")
  TAG_DIR="${BUILD_DIR}/Testing/${TAG}"
  if [ -f "${TAG_DIR}/Test.xml" ]; then
    echo "" >> "${REPORT}"
    echo "### Detailed Timing" >> "${REPORT}"
    echo "" >> "${REPORT}"
    echo "| Test | Status | Time (s) |" >> "${REPORT}"
    echo "|------|--------|----------|" >> "${REPORT}"
    grep '<Test ' "${TAG_DIR}/Test.xml" | while read -r line; do
      TNAME=$(echo "${line}" | sed -n 's/.*Name="\([^"]*\)".*/\1/p')
      TSTAT=$(echo "${line}" | sed -n 's/.*Status="\([^"]*\)".*/\1/p')
      TTIME=$(echo "${line}" | sed -n 's/.*ExecutionTime="\([^"]*\)".*/\1/p')
      echo "| ${TNAME} | ${TSTAT} | ${TTIME} |" >> "${REPORT}"
    done
  fi
fi

echo "" >> "${REPORT}"
echo "---" >> "${REPORT}"
echo "*Report generated by ADCP test suite*" >> "${REPORT}"

echo "Report: ${REPORT}"
cat "${REPORT}"
